import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';
import { useProducersQuery } from '../generated';
import { Navbar, Footer, TestFormPage } from '../components';
import EvaluationFormCheese from '../components/EvaluationFormCheese';
import Hero from '../components/Hero';
const Home: NextPage = () => {
  const { data, error, loading } = useProducersQuery();

  if (loading) return <main className={styles.main}>Loading...</main>;
  if (error) return <main className={styles.main}>{error.message}</main>;

  // From here, { data } can be referenced
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main className="text-3xl font-bold underline text-center">
        <div>Hello, {data?.producers?.data[0].attributes?.name}</div>
      </main>
      <Hero />
      <TestFormPage />
      <EvaluationFormCheese />
      <Footer />
    </div>
  );
};

export default Home;
